export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const UPDATE_ARRIVING_HOUR = "UPDATE_ARRIVING_HOUR";
export const UPDATE_ERROR_M = 'UPDATE_ERROR_M';
export const UPDATE_LOADING = 'UPDATE_LOADING';
export const UPDATE_LUNCHING = 'UPDATE_LUNCHING';
export const UPDATE_LUNCH_BREAK = 'UPDATE_LUNCH_BREAK';


